# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c0089a54e65e35f0c2aad1f23b10e984d69724227c57dc6c9d59475ae18a721319acd2706264f7ce6fac3d0becb3a400be514a44838e011d683be587bd475eda

test:
  secret_key_base: 909f88342972ce25ad7318f1ad44ce226fc5c2acafd014b81dc10a303bb39fb3ce7a9f3e47f05c90480098de733c02d7e5d47ea2b53625f671999f19a16f679a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
